French Translation
CammiesCorner/Arcanus pull request #30
Opened 2024-10-09 15:37 UTC by TathanDev

This PR add support for the French Language

2024-10-09 15:59 UTC, UpcraftLP requested changes
Could you please revert the formatting changes for the en_us file, so that your PR is *only* the french translation?

2024-10-09 16:00 UTC, TathanDev commented
I can but fun fact : when trying to copy paste the file, it's auto-change it ! (But I'll do it)

2024-10-13 22:54 UTC, Pyrofab reviewed
Great job, I can tell a lot of effort went into this. Still, there are a couple typos and missing translations that should probably be fixed before merging.

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"item.arcanuscontinuum.thaumaturges_gauntlet": "Gantelet de la Thaumaturgie",
Why not "Gantelet de Thaumaturge" ?

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"item.arcanuscontinuum.wooden_staff": "Sceptre en Bois",
Style comment that applies to most names here : in French, we don't Use as Many Uppercase Letters as we would in English (specifically the Title Case does not apply) - so for example, "Waxed Oxidized Cut Copper Slab" in the official translation becomes "Dalle de cuivre taillé oxydé ciré". Only Proper Nouns should be capitalized that way.

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"upgrade.arcanuscontinuum.battle_mage_upgrade": "Amélioration en Mage de Guerre",
This translation is fine but it feels a little unnatural considering it's not the equipment itself that is really being turned into a battlemage - would "Amélioration de mage de guerre" do ?

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"item.arcanuscontinuum.smithing_template.battle_mage_upgrade.applies_to": "Armure en Diamand",
```suggestion
	"item.arcanuscontinuum.smithing_template.battle_mage_upgrade.applies_to": "Armure en diamant",
```
Small typo

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"item.arcanuscontinuum.smithing_template.battle_mage_upgrade.base_slot_description": "Ajouter une Armure en Diamand",
```suggestion
	"item.arcanuscontinuum.smithing_template.battle_mage_upgrade.base_slot_description": "Ajouter une armure en diamant",
```
"diamond" is written "diamant" in French, with a "t" instead of a "d"

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"entity.arcanuscontinuum.necro_skeleton": "Necro Squellette",
"Squelette" has a single "L" in French. Also may I suggest a hyphen here ? At least to me, "Necro-squelette" would feel like a more natural name.

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"entity.arcanuscontinuum.guardian_orb": "Orbe du Guardian",
```suggestion
	"entity.arcanuscontinuum.guardian_orb": "Orbe du Guardien",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"entity.arcanuscontinuum.smite": "Rayon Celeste",
```suggestion
	"entity.arcanuscontinuum.smite": "Rayon Céleste",
```
Creative translation, I like it

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"effect.arcanuscontinuum.mana_wings": "Aile de Mana",
Was removing the plural an intentional decision ? It can work, but just wanted to make sure.

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"effect.arcanuscontinuum.stockpile": "Stockpile",
How about "Stockage" ? Or maybe "Réserve" would sound fancier.

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"advancements.arcanuscontinuum.arcane_artifice.title": "Arcane Artifice",
How about "Ingénierie arcanique" ?

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"advancements.arcanuscontinuum.arcane_artifice.description": "Fabriquez un Etablie Arcanique",
```suggestion
	"advancements.arcanuscontinuum.arcane_artifice.description": "Fabriquez un établi arcanique",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"advancements.arcanuscontinuum.wizard_level_10.description": "Atteindre une puissance magique maximale!",
```suggestion
	"advancements.arcanuscontinuum.wizard_level_10.description": "Atteindre une puissance magique maximale !",
```
Again small style thing, unlike in English, interrogation and exclamation points are preceded by a space in French

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"text.arcanuscontinuum.disabled_component": "Ce sort contient un ou plusieurs composants de sort désactivées. Abandon du sort.",
```suggestion
	"text.arcanuscontinuum.disabled_component": "Ce sort contient un ou plusieurs composantes de sort désactivées. Abandon du sort.",
```
Since you wrote "désactivées", I assume you meant to write "composantes", but making them both gramatically masculine could work too (with slightly different implications, "composante" sounds more abstract, which IMO works well for a spell).

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"text.arcanuscontinuum.block_is_warded": "Ce block est protégé.",
```suggestion
	"text.arcanuscontinuum.block_is_warded": "Ce bloc est protégé.",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"text.arcanuscontinuum.too_many_orbs": "That target already has the maximum Aggressorbs!",
```suggestion
	"text.arcanuscontinuum.too_many_orbs": "Cette cible a déjà le maximum d'Agressorbes !",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"spell_component.arcanuscontinuum.rune_shape": "Forme Runique",
In line with the others, shouldn't this be "Forme de rune" ?

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"spell_component.arcanuscontinuum.aggressorb_shape": "Aggressorb Shape",
```suggestion
	"spell_component.arcanuscontinuum.aggressorb_shape": "Forme d'Agressorbe",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"entity.arcanuscontinuum.aggressorb": "Aggressorbe",
```suggestion
	"entity.arcanuscontinuum.aggressorb": "Agressorbe",
```
Only one 'g' to "agression" in French

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"spell_component.arcanuscontinuum.electric_effect": "Effet Electrique",
In line with others, shouldn't this be "Effet d'électricité" ?

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"spell_component.arcanuscontinuum.warding_effect": "Effet de Protéction",
```suggestion
	"spell_component.arcanuscontinuum.warding_effect": "Effet de protection",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"spell_component.arcanuscontinuum.stockpile_effect": "Effet de Renvoie d'Attaque",
Looks like this is the wrong translation - shouldn't this be "Effet de stockage" or "Effet de réserve" ?

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"spell_book.arcanuscontinuum.weight.none": "Auncun",
```suggestion
	"spell_book.arcanuscontinuum.weight.none": "Aucun",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"staff.arcanuscontinuum.primary_color": "Couleur des cristeaux",
```suggestion
	"staff.arcanuscontinuum.primary_color": "Couleur des cristaux",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"door.arcanuscontinuum.not_owner": "Cette porte ne vous appartiens pas",
```suggestion
	"door.arcanuscontinuum.not_owner": "Cette porte ne vous appartient pas",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"door.arcanuscontinuum.password_set": "Le mot de passe defini est %s",
```suggestion
	"door.arcanuscontinuum.password_set": "Le mot de passe défini est %s",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"screen.arcanuscontinuum.tooltip.component_count": "Spell Components",
```suggestion
	"screen.arcanuscontinuum.tooltip.component_count": "Composantes de sort",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"screen.arcanuscontinuum.tooltip.cycle_up": "Skin précedent",
```suggestion
	"screen.arcanuscontinuum.tooltip.cycle_up": "Skin précédente",
```
Mainly wanted to fix the accent, made it grammatically feminine too as it's technically the translation of "peau"

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"wizard_dialogue.arcanuscontinuum.put_on_robes": "Peut être que porté une robe de sorcier vous aidera...",
```suggestion
	"wizard_dialogue.arcanuscontinuum.put_on_robes": "Peut-être que porter une robe de sorcier vous aidera...",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +
The vanilla game translates "killed by magic" with "s'est fait tuer avec un sort", so should probably do the same for these

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"attribute.name.generic.arcanuscontinuum.max_mana": "Mana Maximum",
Sounds like a latin incantation so could be left as is, but could be translated as "Maximum de Mana"

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"attribute.name.generic.arcanuscontinuum.mana_regen": "Regeneration de mana",
```suggestion
	"attribute.name.generic.arcanuscontinuum.mana_regen": "Régéneration de mana",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"attribute.name.generic.arcanuscontinuum.mana_lock": "Réstriction de Mana",
```suggestion
	"attribute.name.generic.arcanuscontinuum.mana_lock": "Restriction de Mana",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"attribute.name.generic.arcanuscontinuum.magic_resistance": "Résistance Magique Rés",
```suggestion
	"attribute.name.generic.arcanuscontinuum.magic_resistance": "Résistance Magique",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +  "attribute.name.generic.arcanuscontinuum.spell_cool_down": "Refroidissement du sort",
```suggestion
  "attribute.name.generic.arcanuscontinuum.spell_cool_down": "Délai entre les sorts",
```
Based on https://fr.minecraft.wiki/w/D%C3%A9g%C3%A2ts#D%C3%A9lai_entre_les_coups

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"config.arcanuscontinuum.attackEffectsCategory": "Effet d'Attaque",
```suggestion
	"config.arcanuscontinuum.attackEffectsCategory": "Effets d'attaque",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"config.arcanuscontinuum.castingSpeedHasCoolDown": "Utiliser le Refroidissement de l'Attaque quand un Sort est Lancé ?",
```suggestion
	"config.arcanuscontinuum.castingSpeedHasCoolDown": "Utiliser le délai entre les coups quand un sort est lancé ?",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"config.arcanuscontinuum.maximumAggressorbs": "Maximum d'Aggressorbs",
```suggestion
	"config.arcanuscontinuum.maximumAggressorbs": "Maximum d'Agressorbes",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"config.arcanuscontinuum.delay": "Delai",
```suggestion
	"config.arcanuscontinuum.delay": "Délai",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"config.arcanuscontinuum.damageNeededToIncrease": "Dégâts Requits pour Augmenter",
```suggestion
	"config.arcanuscontinuum.damageNeededToIncrease": "Dégâts requis pour augmenter la réserve",
```
Took the liberty of adding some context, as the original translation is kind of unclear.

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"config.arcanuscontinuum.baseHealAmount": "Nombre de Point de Guérison de Base",
```suggestion
	"config.arcanuscontinuum.baseHealAmount": "Nombre de points de guérison de base",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +  "config.arcanuscontinuum.guardianOrbShapeProperties": "Forme de l'Orbe du Guardian",
```suggestion
  "config.arcanuscontinuum.guardianOrbShapeProperties": "Forme de l'Orbe du Guardien",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +  "config.arcanuscontinuum.aggressorbShapeProperties": "Aggressorb Shape",
```suggestion
  "config.arcanuscontinuum.aggressorbShapeProperties": "Forme d'Aggressorbe",
```

2024-10-13 22:54 UTC, Pyrofab commented on src/main/resources/assets/arcanuscontinuum/lang/fr_fr.json
> +	"config.arcanuscontinuum.wardingEffectProperties": "Effet de Protéction",
```suggestion
	"config.arcanuscontinuum.wardingEffectProperties": "Effet de Protection",
```

2026-01-25 13:14 UTC, closed without merging